export interface IPartnerSettingReducer {
  servicePointDetails: {
    id: string | null,
    department: string | null,
    name: string | null,
    coc: string | null,
    street: string | null,
    street_number: string | null,
    city: string | null,
    zip_code: string | null,
    lng: string | null,
    lat: string | null,
    country: string | null,
    phone: string | null,
    phone_2: string | null,
    email: string | null,
    website: string | null,
    description: string | null,
    old_service_point_id: number | null,
    opening_hours: any,
    created_at: string | null,
    updated_at: string | null,
    deleted_at: string | null,
    public_visibility: number,
  },
  accessCheck: string,
  loading: boolean,
  error: any,
};
