// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'toggle_collapse_menu';
export const DRAWER_TYPE = 'drawer_type';
export const FIXED_DRAWER = 'fixed_drawer';
export const COLLAPSED_DRAWER = 'collapsible';
export const MINI_DRAWER = 'mini_drawer';
export const THEME_COLOR = 'theme_color';
export const DARK_THEME = 'dark_theme';
export const WINDOW_WIDTH = 'window-width';
export const SWITCH_LANGUAGE = 'switch-language';
export const CHANGE_DIRECTION = 'change-direction';

export const CHANGE_NAVIGATION_STYLE = 'change-navigation-style';
export const HORIZONTAL_NAVIGATION = 'horizontal_navigation';
export const VERTICAL_NAVIGATION = 'vertical_navigation';

export const HORIZONTAL_MENU_POSITION = 'horizontal_menu_position';
export const ABOVE_THE_HEADER = 'above_the_header';
export const INSIDE_THE_HEADER = 'inside_the_header';
export const BELOW_THE_HEADER = 'below_the_header';

//Contact Module const
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'show_message';
export const HIDE_MESSAGE = 'hide_message';

export const FETCH_ALL_CONTACT = 'fetch_all_contact';
export const FETCH_ALL_CONTACT_SUCCESS = 'fetch_all_contact_success';
export const ADD_FAVOURITE = 'add_favourite';
export const ON_CONTACT_SELECT = 'on_contact_select';
export const ON_ADD_CONTACT = 'on_add_contact';
export const ON_CONTACT_CLOSE = 'on_contact_close';
export const ON_FILTER_OPTION_SELECT = 'on_filter_option_select';
export const ON_SAVE_CONTACT = 'on_save_contact';
export const ON_DELETE_CONTACT = 'on_delete_contact';
export const ON_DELETE_SELECTED_CONTACT = 'on_delete_selected_contact';
export const FILTER_CONTACT = 'filter_contact';
export const GET_ALL_CONTACT = 'get_all_contact';
export const GET_UNSELECTED_ALL_CONTACT = 'get_unselected_all_contact';
export const ON_ALL_CONTACT_SELECT = 'on_all_contact_select';
export const UPDATE_SEARCH_USER = 'update_search_user';
export const ON_TOGGLE_DRAWER = 'on_toggle_drawer';
export const HANDLE_REQUEST_CLOSE = 'handle_request_close';
export const HIDE_CONTACT_LOADER = 'hide_contact_loader';

//Auth const
export const SIGNIN_USER = 'signin_user';
export const SIGNIN_USER_SUCCESS = 'signin_user_success';
export const SIGNOUT_USER = 'signout_user';
export const SIGNOUT_USER_SUCCESS = 'signout_user_success';
export const INIT_URL = 'init_url';
export const USER_DATA = 'user_data';
export const USER_TOKEN_SET = 'user_token_set';
export const SOCKET_CONNECTED = 'socket_connected';

// Chat Module const

export const FETCH_ALL_CHAT_USER = 'fetch_all_chat_user';
export const FETCH_ALL_CHAT_USER_CONVERSATION = 'fetch_all_chat_user_conversation';
export const FETCH_ALL_CHAT_USER_SUCCESS = 'fetch_all_chat_user_success';
export const FETCH_ALL_CHAT_USER_CONVERSATION_SUCCESS = 'fetch_all_chat_user_conversation_success';
export const FILTER_USERS = 'filter_users';
export const ON_SELECT_USER = 'on_select_user';
export const ON_SHOW_LOADER = 'on_show_loader';
export const ON_HIDE_LOADER = 'on_hide_loader';
export const USER_INFO_STATE = 'user_info_state';
export const SUBMIT_COMMENT = 'submit_comment';
export const UPDATE_MESSAGE_VALUE = 'update_message_value';
export const UPDATE_SEARCH_CHAT_USER = 'update_search_chat_user';

//// Mail Module const

export const ADD_LABEL = 'ADD_LABEL';
export const GET_ALL_MAIL = 'get_all_mail';
export const FETCH_ALL_USER_ASSOCIATED_MAILS = 'fetch_all_mail';
export const FETCH_FOLDERS = 'fetch_folders';
export const FETCH_FOLDER_EMAILS = 'fetch_folder_emails';
export const FETCH_START_EMAILS = 'fetch_start_emails';
export const FETCH_MAIL_ERROR = 'fetch_mail_error';
export const FETCH_ALL_MAIL_SUCCESS = 'fetch_all_mail_success';
export const GET_IMPORTANT_MAIL = 'get_important_mail';
export const GET_NAV_FILTERS = 'get_nav_filters';
export const GET_NAV_LABELS = 'get_nav_labels';
export const GET_NAV_FOLDER = 'get_nav_folder';
export const GET_READ_MAIL = 'get_read_mail';
export const GET_STARRED_MAIL = 'get_starred_mail';
export const GET_UNIMPORTANT_MAIL = 'get_unimportant_mail';
export const GET_UNREAD_MAIL = 'get_unread_mail';
export const GET_UNSELECTED_ALL_MAIL = 'get_unselected_all_mail';
export const GET_UNSTARRED_MAIL = 'get_unstarred_mail';
export const ON_ALL_MAIL_SELECT = 'on_all_mail_select';
export const ON_FOLDER_MENU_ITEM_SELECT = 'on_folder_menu_item_select';
export const ON_FOLDER_SELECT = 'on_folder_select';
export const ON_IMPORTANT_SELECT = 'on_important_select';
export const ON_LABEL_MENU_ITEM_SELECT = 'on_label_menu_item_select';
export const GET_MARK_AS_START = 'get_mark_as_start';
export const ON_LABEL_SELECT = 'on_label_select';
export const ON_MAIL_CHECKED = 'on_mail_checked';
export const ON_MAIL_SELECT = 'on_mail_select';
export const ON_MAIL_SEND = 'on_mail_send';
export const ON_OPTION_MENU_ITEM_SELECT = 'on_option_menu_item_select';
export const ON_OPTION_MENU_SELECT = 'on_option_menu_select';
export const ON_START_SELECT = 'on_start_select';
export const SEARCH_MAIL = 'search_mail';
export const ON_DELETE_MAIL = 'on_delete_mail';
export const SET_CURRENT_MAIL_NULL = 'set_current_mail_null';
export const ON_COMPOSE_MAIL = 'on_compose_mail';
export const SET_RESPONSE_OBJECT = 'SET_RESPONSE_OBJECT';

//// TO-DO Module const

export const ON_SORTEND = 'on_sortend';
export const FETCH_ALL_TODO = 'fetch_all_todo';
export const FETCH_ALL_TODO_SUCCESS = 'fetch_all_todo-success';
export const FETCH_ALL_TODO_CONVERSATION = 'fetch_all_todo_conversation';
export const FETCH_ALL_TODO_CONVERSATION_SUCCESS = 'fetch_all_todo_conversation_success';
export const SELECT_ALL_TODO = 'select_all_todo';
export const GET_ALL_TODO = 'get_all_todo';
export const GET_UNSELECTED_ALL_TODO = 'get_unselected_all_todo';
export const GET_STARRED_TODO = 'get_starred_todo';
export const GET_UNSTARRED_TODO = 'get_unstarred_todo';
export const GET_IMPORTANT_TODO = 'get_important_todo';
export const GET_UNIMPORTANT_TODO = 'get_unimportant_todo';
export const ON_LABEL_UPDATE = 'on_label_update';
export const ON_TODO_UPDATE = 'on_todo_update';
export const ON_DELETE_TODO = 'on_delete_todo';
export const SEARCH_TODO = 'search_todo';
export const SHOW_TODOS = 'show_todos';
export const GET_TODO_CONVERSATION = 'get_todo_conversation';
export const ON_TODO_CHECKED = 'on_todo_checked';
export const ON_TODO_ADD = 'on_todo_add';
export const ON_TODO_SELECT = 'on_todo_select';
export const SET_CURRENT_TODO_NULL = 'set_current_todo_null';
export const REMOVE_LABEL = 'remove_label';
export const UPDATE_SEARCH = 'update_search';

// DEPARTMENT ACTIONS
export const DEPARTMENT_DATA = 'DEPARTMENT_DATA';
export const SELECTED_DEPARTMENT = 'SELECTED_DEPARTMENT';
export const DEPARTMENT_ERROR = 'DEPARTMENT_ERROR';

// SOFTPHONE ACTIONS
export const OPENDIAL = 'OPENDIAL';
export const DIAL_NUMBER = 'DIAL_NUMBER';
export const ESTABLISH_CALL = 'ESTABLISH_CALL';
export const SET_CALLER_NAME = 'SET_CALLER_NAME';
export const SET_CALLER_AVATAR = 'SET_CALLER_AVATAR';
export const CALL_CONNECTED = 'CALL_CONNECTED';
export const SAVE_DEVICE_TOKEN = 'SAVE_DEVICE_TOKEN';
export const INCREMENT_CALL_TIMER = 'INCREMENT_CALL_TIMER';
export const TOGGLE_MUTE = 'TOGGLE_MUTE';
export const CALL_DISCONNECT = 'CALL_DISCONNECT';
export const CALL_HOLD = 'CALL_HOLD';
export const SET_DEVICE_READY = 'SET_DEVICE_READY';
export const HIDE_POPUP = 'HIDE_POPUP';
export const SHOW_POPUP = 'SHOW_POPUP';
export const SHOW_CALL_LISTENING_POPUP = 'SHOW_CALL_LISTENING_POPUP';
export const HIDE_CALL_LISTENING_POPUP = 'HIDE_CALL_LISTENING_POPUP';
export const SET_CALL_INIT_FALSE = 'SET_CALL_INIT_FALSE';
export const ON_CALL_NUMBERPAD = 'ON_CALL_NUMBERPAD';
export const ACTIVE_CALL_NUMBERPAD_TOGGLE = 'ACTIVE_CALL_NUMBERPAD_TOGGLE';
export const ACTIVE_CALL_FORWARDPAD_TOGGLE = 'ACTIVE_CALL_FORWARDPAD_TOGGLE';
export const INCOMING_CALL = 'INCOMING_CALL';
export const REJECT_CALL = 'REJECT_CALL';
export const GET_AGENT = 'GET_AGENT';
export const GET_AGENT_FAIL = 'GET_AGENT_FAIL';
export const SET_CALL_INVITE_ERROR = 'SET_CALL_INVITE_ERROR';
export const RESET_CALL_INVITE_ERROR = 'RESET_CALL_INVITE_ERROR';
export const START_CALLHISTORY_LOADING = 'START_CALLHISTORY_LOADING';
export const CLEAR_CALLHISTORY_DATA = 'CLEAR_CALLHISTORY_DATA';
export const GET_CALLHISTORY_DATA = 'GET_CALLHISTORY_DATA';
export const GET_CALLHISTORY_ERROR = 'GET_CALLHISTORY_ERROR';
export const GET_AGENTS_NUMBERS = 'GET_AGENTS_NUMBERS';

// CALLQUEUELIST ACTIONS
export const CALL_QUEUE_LIST = 'CALL_QUEUE_LIST';
export const SET_CALL_QUEUE_STATUS = 'SET_CALL_QUEUE_STATUS';
export const SET_CALL_QUEUE_ID = 'SET_CALL_QUEUE_ID';
export const TOGGLE_SPINNER = 'TOGGLE_SPINNER';
export const TOGGLE_ALERT_PROMPT = 'TOGGLE_ALERT_PROMPT';
export const SET_ACTIVE_CALLER = 'SET_ACTIVE_CALLER';
export const SET_TIMER = 'SET_TIMER';
export const SET_NO_ACTION = 'SET_NO_ACTION';
export const SET_ACTIVE_CALLER_AFTER_DELETE = 'SET_ACTIVE_CALLER_AFTER_DELETE';
export const SET_PROMPT_SHOW = 'SET_PROMPT_SHOW';
export const SET_COMMENTS_DATA = 'SET_COMMENTS_DATA';
export const SET_CALL_QUEUE_LOADER_FALSE = 'SET_CALL_QUEUE_LOADER_FALSE';
export const SET_SNACKBAR_TRUE = 'SET_SNACKBAR_TRUE';
export const SET_CALL_QUEUE_ID_DATA = 'SET_CALL_QUEUE_ID_DATA';
export const EDIT_CALL_QUEUE_ID = 'EDIT_CALL_QUEUE_ID';
export const EDIT_CALL_QUEUE_NAME = 'EDIT_CALL_QUEUE_NAME';
export const EDIT_CALL_QUEUE_DESCRIPTION = 'EDIT_CALL_QUEUE_DESCRIPTION';
export const EDIT_CALL_QUEUE_IMAGE = 'EDIT_CALL_QUEUE_IMAGE';
export const EDIT_CALL_QUEUE_DEPARTMENT = 'EDIT_CALL_QUEUE_DEPARTMENT';
export const EDIT_CALL_QUEUE_ORDER = 'EDIT_CALL_QUEUE_ORDER';
export const EDIT_CALL_QUEUE_CREATED_AT = 'EDIT_CALL_QUEUE_CREATED_AT';
export const EDIT_CALL_QUEUE_UPDATED_AT = 'EDIT_CALL_QUEUE_UPDATED_AT';
export const EDIT_CALL_QUEUE_SUCCESS_TOGGLE = 'EDIT_CALL_QUEUE_SUCCESS_TOGGLE';
export const EDIT_CALL_QUEUE_WARNING_TOGGLE = 'EDIT_CALL_QUEUE_WARNING_TOGGLE';
export const TOGGLE_ALERT_POPUP = 'TOGGLE_ALERT_POPUP';

// NOTIFICATION ACTIONS
export const SET_SHOW_MESSAGE_URL = 'SET_SHOW_MESSAGE_URL';
export const SET_NOTIFICATION_HIDE = 'SET_NOTIFICATION_HIDE';
export const SET_SNACKBAR_SHOW = 'SET_SNACKBAR_SHOW';

//CALLQUEUEOVERVIEW ACTIONS
export const SET_CALL_QUEUE_OVERVIEW_DATA = 'SET_CALL_QUEUE_OVERVIEW_DATA';

//SUPPORT ACTIONS
export const SUPPORT_PHONE_SYSTEMS_CALL_HISTORIES = 'SUPPORT_PHONE_SYSTEMS_CALL_HISTORIES';
export const SUPPORT_PHONE_SYSTEMS_CALL_HISTORIES_META = 'SUPPORT_PHONE_SYSTEMS_CALL_HISTORIES_META';
export const SUPPORT_PHONE_SYSTEMS_CALL_HISTORIES_RECORDINGS = 'SUPPORT_PHONE_SYSTEMS_CALL_HISTORIES_RECORDINGS';

//EMPLOYEE TABLE ACTIONS
export const SET_EMPLOYEES_TABLE_DATA = 'SET_EMPLOYEES_TABLE_DATA';
export const SET_IS_EMPLOYEE_TABLE_LOADING_TRUE = 'SET_IS_EMPLOYEE_TABLE_LOADING_TRUE';
export const SET_IS_EMPLOYEE_TABLE_LOADING_FALSE = 'SET_IS_EMPLOYEE_TABLE_LOADING_FALSE';
export const SET_ROLES = 'SET_ROLES';
export const SET_COUNTRY_CODES = 'SET_COUNTRY_CODES';
export const SET_FIRST_NAME = 'SET_FIRST_NAME';
export const SET_LAST_NAME = 'SET_LAST_NAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PHONE_COUNTRY = 'SET_PHONE_COUNTRY';
export const SET_PHONE = 'SET_PHONE';
export const SET_ROLE = 'SET_ROLE';
export const RESET_EMPLOYEE_DETAILS = 'RESET_EMPLOYEE_DETAILS';
export const SET_SUBMIT_DISABLE = 'SET_SUBMIT_DISABLE';
export const SET_SUBMIT_ENABLE = 'SET_SUBMIT_ENABLE';
export const SET_SUCCESS_TRUE = 'SET_SUCCESS_TRUE';
export const SET_WARNING_TRUE =  'SET_WARNING_TRUE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_SUCCESS_FALSE = 'SET_SUCCESS_FALSE';
export const SET_WARNING_FALSE = 'SET_SUCCESS_FALSE';
export const SET_POPUP_TRUE = 'SET_POPUP_TRUE';
export const HIDE_ALERT_POPUP = 'HIDE_ALERT_POPUP';
export const DELETE_EMPLOYEE_RECORD = 'DELETE_EMPLOYEE_RECORD';
export const ADD_EMPLOYEES_TABLE_DATA = 'ADD_EMPLOYEES_TABLE_DATA';

//COMPANIES ACTION
export const GET_COMPANY_DETAILS = 'GET_COMPANIES_DETAILS';
export const CLEAR_COMPANY_DATA = 'CLEAR_COMPANY_DATA';
export const GET_QUEUE_ENTRIES = 'GET_CALL_QUEUE_ENTRIES';
export const GET_QUEUE_ENTRIES_ERROR = 'GET_CALL_QUEUE_ENTRIES_ERROR';
export const SEARCH_QUEUE_ENTRIES = 'SEARCH_QUEUE_ENTRIES';
export const SEARCH_QUEUE_ENTRIES_ERROR = 'SEARCH_QUEUE_ENTRIES_ERROR';
export const CLEAR_DATA = 'CLEAR_DATA';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const UPDATE_COMPANY_OPENING_HOUR = 'UPDATE_COMPANY_OPENING_HOUR';
export const DELETE_RECOGNITION = 'DELETE_RECOGNITION';
export const DELETE_RECOGNITION_ERROR = 'DELETE_RECOGNITION_ERROR';

//SERVICE DROPDOWN
export const SERVICEPOINT_DATA = 'SERVICEPOINT_DATA';
export const SELECTED_SERVICEPOINT = 'SELECTED_SERVICEPOINT';
export const SERVICEPOINT_ACCESS_CHECK = 'SERVICEPOINT_ACCESS_CHECK';

//EMPLOYEES ACTION
export const GET_EMPLOYEE_LIST = 'GET_EMPLOYEE_LIST';
export const START_EMPLOYEE_LOADING = 'START_EMPLOYEE_LOADING';
export const SET_EMPLOYEE_ERROR = 'SET_EMPLOYEE_ERROR';

//SERVICES ACTION
export const GET_SERVICES_LIST = 'GET_SERVICES_LIST';
export const START_SERVICES_LOADING = 'START_SERVICES_LOADING';
export const STOP_SERVICES_LOADING = 'STOP_SERVICES_LOADING';
export const SET_SERVICES_ERROR = 'SET_SERVICES_ERROR';
export const GET_SERVICE_CATEGORIES = 'GET_SERVICE_CATEGORIES';
export const GET_SERVICE_PRICE_DRIVER = 'GET_SERVICE_PRICE_DRIVER';
export const RESET_SERVICE_ERROR = 'RESET_SERVICE_ERROR';

//ORDER ACTION
export const GET_ORDER_OVERVIEW = 'GET_ORDER_OVERVIEW';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL';
export const CLEAR_CANCEL_ORDER = 'CLEAR_CANCEL_ORDER';
export const CLEAR_ORDER_OVERVIEW = 'CLEAR_ORDER_OVERVIEW';
export const GET_NEARBY_SERVICE_POINT = 'GET_NEARBY_SERVICE_POINT';
export const GET_SERVICE_POINT_DETAILS = 'GET_SERVICE_POINT_DETAILS';
export const GET_ORDER_LIST = 'GET_ORDER_LIST';
export const GET_PREFERRED_DATES = "GET_PREFERRED_DATES";
export const CREATE_PREFERRED_DATE = "CREATE_PREFERRED_DATE";
export const UPDATE_PREFERRED_DATE = "UPDATE_PREFERRED_DATE";
export const DELETE_PREFERRED_DATE_SUCCESS = "DELETE_PREFERRED_DATE_SUCCESS";
export const DELETE_PREFERRED_DATE_REQUEST = "DELETE_PREFERRED_DATE_REQUEST";
export const DELETE_PREFERRED_DATE_ERROR = "DELETE_PREFERRED_DATE_ERROR";

//ORDER CREATE ACTION
export const SET_NEW_ORDER = 'SET_NEW_ORDER';
export const GET_SERVICE = 'GET_SERVICE';
export const UPDATE_SERVICE_PRICE = 'UPDATE_SERVICE_PRICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const GET_SERVICE_FAIL = 'GET_SERVICE_FAIL';
export const SET_SELECTED_SERVICE = 'SET_SELECTED_SERVICE';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER';
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL';
export const SET_SERVICE_PRICE = 'SET_SERVICE_PRICE';
export const RESET_SERVICE_DATA = 'RESET_SERVICE_DATA';
export const SET_ORDER_DETAIL = 'SET_ORDER_DETAIL';
export const SET_COURIER_TYPE = 'SET_COURIER_TYPE';
export const SET_DIMENSION_DATA = 'SET_DIMENSION_DATA';
export const SET_SERVICE_DATA = 'SET_SERVICE_DATA';
export const RESET_ORDER = 'RESET_ORDER';
export const SUBMIT_ORDER_FAIL = 'SUBMIT_ORDER_FAIL';
export const SET_SUPPORTCODE_DATA = 'SET_SUPPORTCODE_DATA';
export const GET_AUTOCOMPLETE_DATA_SUCCESS = 'GET_AUTOCOMPLETE_DATA_SUCCESS';
export const GET_AUTOCOMPLETE_DATA_FAIL = 'GET_AUTOCOMPLETE_DATA_FAIL';
export const RESET_AUTOCOMPLETE_DATA = 'RESET_AUTOCOMPLETE_DATA';
export const SET_SELECTED_COURIER_VEHICLE = 'SET_SELECTED_COURIER_VEHICLE';
export const SET_ORDER_PREFILL_DATA = 'SET_ORDER_PREFILL_DATA';
export const GET_COURIER_VEHICLELIST = 'GET_COURIER_VEHICLELIST';
export const SET_SELECTED_SHIPMENT = 'SET_SELECTED_SHIPMENT';
export const GET_PAYMENT_OPTION = 'GET_PAYMENT_OPTION';
export const GET_DELIVERY_OPTION = 'GET_DELIVERY_OPTION';
export const GET_SUBSCRIPTION_LIST = 'GET_SUBSCRIPTION_LIST';
export const START_SUBSCRIPTION_LOADING = 'START_SUBSCRIPTION_LOADING';
export const STOP_SUBSCRIPTION_LOADING = 'STOP_SUBSCRIPTION_LOADING';
export const SET_SUBSCRIPTION_ERROR = 'SET_SUBSCRIPTION_ERROR';
export const UPDATE_CLIENT_DETIALS = 'UPDATE_CLIENT_DETIALS';
export const UPDATE_RECIEVER_DETIALS = 'UPDATE_RECIEVER_DETIALS';
export const UPDATE_SENDER_DETIALS = 'UPDATE_SENDER_DETIALS';
export const UPDATE_OTHER_DETIALS = 'UPDATE_OTHER_DETIALS';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const UPDATE_SENDER = 'UPDATE_SENDER';
export const UPDATE_RECIEVER = 'UPDATE_RECIEVER';
export const UPDATE_ALL_DETAILS = 'UPDATE_ALL_DETAILS';

export const START_INVOICE_LOADING = 'START_INVOICE_LOADING';
export const GET_INVOICE_LIST = 'GET_INVOICE_LIST';
export const GET_INVOICE_META = 'GET_INVOICE_META';
export const SET_INVOICE_ERROR = 'SET_INVOICE_ERROR';
export const STOP_INVOICE_LOADING = 'STOP_INVOICE_LOADING';

//ROLE ACTION
export const SET_ROLE_INFO = 'SET_ROLE_INFO';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const CHECK_SUBMIT_BUTTON_STATUS = 'CHECK_SUBMIT_BUTTON_STATUS';
export const SET_CREATEROLE_POPUP_TRUE = 'SET_CREATEROLE_POPUP_TRUE';
export const SET_CREATEROLE_POPUP_FALSE = 'SET_CREATEROLE_POPUP_FALSE';
export const SET_SUCCESS_VALUE_FALSE = 'SET_SUCCESS_VALUE_FALSE';
export const SET_SUCCESS_VALUE_TRUE = 'SET_SUCCESS_VALUE_TRUE';
export const SET_WARNING_VALUE_FALSE = 'SET_WARNING_VALUE_FALSE';
export const SET_WARNING_VALUE_TRUE = 'SET_WARNING_VALUE_TRUE';
export const SET_ALERT_POPUP_VALUE_FALSE = 'SET_ALERT_POPUP_VALUE_FALSE';
export const SET_ALERT_POPUP_VALUE_TRUE = 'SET_ALERT_POPUP_VALUE_TRUE';
export const SET_RESPONSE_ERROR_MESSAGE = 'SET_RESPONSE_ERROR_MESSAGE';
export const SET_ROLE_LOADING_TRUE = 'SET_ROLE_LOADING_TRUE';
export const SET_ROLE_LOADING_FALSE = 'SET_ROLE_LOADING_FALSE';
export const SET_ROLE_TABLE_DATA = 'SET_ROLE_TABLE_DATA';
export const ADD_ROLE_TABLE_DATA = 'ADD_ROLE_TABLE_DATA';
export const ADD_CREATED_ROLE = 'ADD_CREATED_ROLE';
export const DELETE_ROLE_TABLE_DATA = 'DELETE_ROLE_TABLE_DATA';
export const SET_SELECTED_SERVICES = 'SET_SELECTED_SERVICES'
export const SET_CUSTOM_DESCRIPTION = 'SET_CUSTOM_DESCRIPTION'

//ABILITY ACTION
export const SET_ABILITY_INFO = 'SET_ABILITY_INFO';
export const SET_ABILITY_DESCRIPTION = 'SET_ABILITY_DESCRIPTION';
export const CHECK_ABILITY_SUBMIT_BUTTON_STATUS = 'CHECK_ABILITY_SUBMIT_BUTTON_STATUS';
export const SET_CREATE_ABILITY_POPUP_TRUE = 'SET_CREATE_ABILITY_POPUP_TRUE';
export const SET_CREATE_ABILITY_POPUP_FALSE = 'SET_CREATE_ABILITY_POPUP_FALSE';
export const SET_ABILITY_SUCCESS_VALUE_FALSE = 'SET_ABILITY_SUCCESS_VALUE_FALSE';
export const SET_ABILITY_WARNING_VALUE_FALSE = 'SET_ABILITY_WARNING_VALUE_FALSE';
export const SET_ABILITY_WARNING_VALUE_TRUE = 'SET_ABILITY_WARNING_VALUE_TRUE';
export const SET_ABILITY_ALERT_POPUP_VALUE_FALSE = 'SET_ABILITY_ALERT_POPUP_VALUE_FALSE';
export const SET_ABILITY_SUCCESS_VALUE_TRUE = 'SET_ABILITY_SUCCESS_VALUE_TRUE';
export const SET_ABILITY_ALERT_POPUP_VALUE_TRUE = 'SET_ABILITY_ALERT_POPUP_VALUE_TRUE';
export const SET_ABILITY_RESPONSE_ERROR_MESSAGE = 'SET_ABILITY_RESPONSE_ERROR_MESSAGE';

// PERMISSION ACTION
export const  GET_ALL_PERMISSION = 'GET_ALL_PERMISSION';

//ORDER PAGE ACTIONS
export const SET_DATA_LIST = 'SET_DATA_LIST';

//PARTNER SETTING ACTION
export const SET_SERVICEPOINT_DETAILS = 'SET_SERVICEPOINT_DETAILS';
export const SET_ADDRESS_LINE_ONE = 'SET_ADDRESS_LINE_ONE';
export const SET_ADDRESS_LINE_THREE = 'SET_ADDRESS_LINE_THREE';
export const SET_PARTNER_NAME = 'SET_PARTNER_NAME';
export const SET_PARTNER_CONTACT = 'SET_PARTNER_CONTACT';
export const SET_PARTNER_PHONE = 'SET_PARTNER_PHONE';
export const SET_PARTNER_EMAIL = 'SET_PARTNER_EMAIL';
export const SET_PARTNER_ADDRESS_LINEONE = 'SET_PARTNER_ADDRESS_LINEONE';
export const SET_PARTNER_ZIPCODE = 'SET_PARTNER_ZIPCODE';
export const SET_PARTNER_ADDRESS_LINETHREE = 'SET_PARTNER_ADDRESS_LINETHREE';
export const SET_PARTNER_PHONE_TWO = 'SET_PARTNER_PHONE_TWO';
export const SET_PARTNER_WEBSITE = 'SET_PARTNER_WEBSITE';
export const SET_PARTNER_DESCRIPTION = 'SET_PARTNER_DESCRIPTION';
export const SET_PARTNER_COC = 'SET_PARTNER_COC';
export const SET_PARTNER_STREET = 'SET_PARTNER_STREET';
export const SET_PARTNER_CITY = 'SET_PARTNER_CITY';
export const SET_PARTNER_STREET_NUMBER = 'SET_PARTNER_STREET_NUMBER';
export const SET_PARTNER_VISIBILITY = 'SET_PARTNER_VISIBILITY';
export const SET_PARTNER_TYPE_ID = 'SET_PARTNER_TYPE_ID';
export const UPDATE_SERVICEPOINT_DETAILS = 'UPDATE_SERVICEPOINT_DETAILS';
export const START_PARTNER_LOADING = 'START_PARTNER_LOADING';
export const STOP_PARTNER_LOADING = 'STOP_PARTNER_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const RESET_ERROR = 'RESET_ERROR';

// MARKETING ACTION
export const GET_CAMPAIGN_OVERVIEW = 'GET_CAMPAIGN_OVERVIEW';
export const ADD_CAMPAIGN = 'ADD_CAMPAIGN';
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const ERROR_ADD_CAMPAIGN = 'ERROR_ADD_CAMPAIGN';
export const GET_CAMPAIGN = 'GET_CAMPAIGN';
export const GET_EMAIL_OPENS = 'GET_EMAIL_OPENS';
export const GET_EMAIL_UNSUBSCRIBE = 'GET_EMAIL_UNSUBSCRIBE';
export const GET_OUTBOX_MESSAGE = 'GET_OUTBOX_MESSAGE';
export const GET_EMAIL_TEMPLATES = 'GET_EMAIL_TEMPLATES';
export const GET_STATUS = 'GET_STATUS';

//PARTNER EMPLOYEES
export const GET_PARTNER_EMPLOYEES = 'GET_PARTNER_EMPLOYEES';

//DASHBOARD
export const GET_DASHBOARD_ORDER = "GET_DASHBOARD_ORDER";
export const START_DASHBOARD_LOADING = "START_DASHBOARD_LOADING";

//ADMIN EMPLOYEE
export const GET_ADMIN_EMPLOYEE_DATA = "GET_ADMIN_EMPLOYEE_DATA";
export const START_ADMIN_EMPLOYEE_LOADING = "START_ADMIN_EMPLOYEE_LOADING";
export const STOP_ADMIN_EMPLOYEE_LOADING = "STOP_ADMIN_EMPLOYEE_LOADING";
export const SET_ADMIN_EMPLOYEE_ERROR = "SET_ADMIN_EMPLOYEE_ERROR";
export const GET_ADMIN_EMPLOYEE_PERMISSION = "GET_ADMIN_EMPLOYEE_PERMISSION";
export const START_ADMIN_EMPLOYEE_PERMISSION_LOADING = "START_ADMIN_EMPLOYEE_PERMISSION_LOADING";
export const STOP_ADMIN_EMPLOYEE_PERMISSION_LOADING = "STOP_ADMIN_EMPLOYEE_PERMISSION_LOADING";
export const SET_ADMIN_EMPLOYEE_PERMISSION_ERROR = "SET_ADMIN_EMPLOYEE_PERMISSION_ERROR";
export const GET_ADMIN_EMPLOYEE_CREDENTIAL = "GET_ADMIN_EMPLOYEE_CREDENTIAL";
export const START_ADMIN_EMPLOYEE_CREDENTIAL_LOADING = "START_ADMIN_EMPLOYEE_CREDENTIAL_LOADING";
export const STOP_ADMIN_EMPLOYEE_CREDENTIAL_LOADING = "STOP_ADMIN_EMPLOYEE_CREDENTIAL_LOADING";
export const SET_ADMIN_EMPLOYEE_CREDENTIAL_ERROR = "SET_ADMIN_EMPLOYEE_CREDENTIAL_ERROR";
export const DELETE_ADMIN_EMPLOYEE_CREDENTIAL = "DELETE_ADMIN_EMPLOYEE_CREDENTIAL";


//FEEDBACK
export const GET_FEEDBACK = "GET_FEEDBACK";
export const START_FEEDBACK_LOADING = "START_FEEDBACK_LOADING";
export const STOP_FEEDBACK_LOADING = "STOP_FEEDBACK_LOADING";
export const SET_FEEDBACK_ERROR = "SET_FEEDBACK_ERROR";
export const FEEDBACK_ACTION_SUCCESS = "FEEDBACK_ACTION_SUCCESS";

//REPROT
export const START_REPORT_LOADING = "START_REPORT_LOADING";
export const GET_REPORT = "GET_REPORT";
export const SET_REPORT_ERROR="SET_REPORT_ERROR";
export const REPORT_ACTION_SUCCESS = "REPORT_ACTION_SUCCESS";
export const STOP_REPORT_LOADING = "STOP_REPORT_LOADING";

//SERVICE POINT ACTIONS
export const GET_SERVICE_POINT_DISSOCIATION_REASON_REQUEST = "GET_SERVICE_POINT_DISSOCIATION_REASON_REQUEST"
export const GET_SERVICE_POINT_DISSOCIATION_REASON_SUCCESS = "GET_SERVICE_POINT_DISSOCIATION_REASON_SUCCESS"
export const GET_SERVICE_POINT_DISSOCIATION_REASON_ERROR = "GET_SERVICE_POINT_DISSOCIATION_REASON_ERROR"

export const SET_SERVICE_POINT_DISSOCIATION_REQUEST = "SET_SERVICE_POINT_DISSOCIATION_REQUEST"
export const SET_SERVICE_POINT_DISSOCIATION_SUCCESS = "SET_SERVICE_POINT_DISSOCIATION_SUCCESS"
export const SET_SERVICE_POINT_DISSOCIATION_ERROR = "SET_SERVICE_POINT_DISSOCIATION_ERROR"
